---
- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: "ansible2-instance"
    instance_type: "{{ type }}"
    security_group: default
    region: us-east-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    image_id: ami-0866a3c8686eaeeba
    tags:
      Environment: Testing
    network:
      assign_public_ip: yes  # Use 'assign_public_ip' under the 'network' parameter
  register: ec2_instance

- name: Debug EC2 instance creation result
  debug:
    var: ec2_instance

